feat: add_Pagabreaks_A3PageSize
fumiama/go-docx pull request #20
Opened 2024-03-16 13:01 UTC by mabiao0525

feat: add_pagebreaks
feat: add_A3PageSize
fix: addText

2024-03-16 14:54 UTC, fumiama requested changes
一般来说，两个不同方向的更改应该分两次提交。不过这次就算了吧。

2024-03-16 14:54 UTC, fumiama commented on apitext.go
> +			if s != "" {
`if k != ""`

2024-03-16 14:54 UTC, fumiama commented on structdoc.go
> +	PgSz PgSz `xml:"w:pgSz"` // paper size
`PgSz *PgSz`并omitempty

2024-03-16 14:54 UTC, fumiama commented on theme.go
> +	f.Document.Body.SectPr.PgSz.W = xml.Attr{Name: xml.Name{Local: "w:w"}, Value: "11906"}
xml.Name不用管他。

2024-03-16 14:54 UTC, fumiama commented on theme.go
> +	f.Document.Body.SectPr.PgSz.W = xml.Attr{Name: xml.Name{Local: "w:w"}, Value: "16838"}
建议直接
```go
f.Document.Body.Items = append(f.Document.Body.Items, &SectPr{...})
```

2024-03-16 14:54 UTC, fumiama commented on structdoc.go
> +	SectPr SectPr `xml:"w:sectPr,omitempty"` // properties of the document, including paper size
SectPr亦属Items，不必在此单列。至于如何解析，请在

https://github.com/fumiama/go-docx/blob/047c5e5f0306a2a2ddb59630c494648d254e4ffd/structdoc.go#L65-L102

添加相关内容。

2024-03-16 15:20 UTC, mabiao0525 commented on theme.go
> +	f.Document.Body.SectPr.PgSz.W = xml.Attr{Name: xml.Name{Local: "w:w"}, Value: "11906"}
这里没太明白你的意思，如果这里f.Document.Body.SectPr.PgSz.W = xml.Attr{Value: "11906"}这样写的话，就无法正常使用getAtt函数了吧，无法找到Name.Local

2024-03-16 16:56 UTC, fumiama commented on theme.go
> +	f.Document.Body.SectPr.PgSz.W = xml.Attr{Name: xml.Name{Local: "w:w"}, Value: "11906"}
你去掉试试呗，不影响的应该。

2024-03-16 16:57 UTC, fumiama commented on theme.go
> +	f.Document.Body.SectPr.PgSz.W = xml.Attr{Name: xml.Name{Local: "w:w"}, Value: "11906"}
getAtt是给解码用的，这边不用管他。

2024-03-16 17:03 UTC, fumiama requested changes
分开的好处是一个改好之后我就可以直接合并了。现在你pagebreak部分虽然没问题，但是我还是要等你这个再改完才能合。

2024-03-16 17:03 UTC, fumiama commented on structdoc.go
> +				err = d.DecodeElement(&value, &tt)
你写完自己测过没有，这个要成功的前提是给SectPr结构体自定义`UnmarshalXML`方法。你可参考`<p>`标签：

https://github.com/fumiama/go-docx/blob/047c5e5f0306a2a2ddb59630c494648d254e4ffd/structpara.go#L229

2024-03-16 17:06 UTC, fumiama requested changes

2024-03-16 17:06 UTC, fumiama commented on structdoc.go
> +type SectPr struct {
另外，建议把这个结构体及其相关内容移到新文件`structsect.go`

2024-03-17 02:52 UTC, mabiao0525 commented on structdoc.go
> +	XMLName xml.Name `xml:"w:sectPr,omitempty"` // properties of the document, including paper size
好的，我将两次分开，因为我看之前没加<w: pgSz>是默认A4模板的，这里不用omitempty吗？

2024-03-17 02:58 UTC, mabiao0525 commented on structdoc.go
> +	XMLName xml.Name `xml:"w:pgSz,omitempty"`
我看大标签是<w:secPr>所以在SectPr结构体内，写了XMLName xml.Name `xml:"w:sectPr,omitempty"`，并加入PgSz，因为PgSz是<w:secPr>标签下的一个标签，然后W，H是他的属性，所以才这样写，不应该这样写吗？

2024-03-17 10:59 UTC, fumiama commented on structdoc.go
> +	XMLName xml.Name `xml:"w:pgSz,omitempty"`
这样写可以啊，但是小结构体就按之前写法呗，你之前咋写的，就忘了吗

![](https://github.com/fumiama/go-docx/assets/41315874/0d54f408-dd28-4cc6-9e5b-af439049d932)

2024-03-17 11:00 UTC, fumiama commented on structdoc.go
> +	XMLName xml.Name `xml:"w:pgSz,omitempty"`
当然，`*PgSz`要改。

2024-03-19 03:18 UTC, closed without merging