feat: A3PageSize
fumiama/go-docx pull request #22
Opened 2024-03-17 12:54 UTC by mabiao0525

编码，解码测试过，可以成功获取SectPr属性

2024-03-18 07:10 UTC, fumiama requested changes
不错不错

2024-03-18 07:10 UTC, fumiama commented on structdoc_test.go
> +		if len(doc.Body.Items) != tc.numParagraphs+1 { // the 1 is the sectPr
直接给上面`numParagraphs`各加一即可。

2024-03-18 07:10 UTC, fumiama commented on structsect.go
> +   Copyright (c) 2023 Fumiama Minamoto (源文雨)
这个文件是纯由你编写，应当写上你的名字而非我的。

2024-03-18 07:10 UTC, fumiama commented on structsect.go
> +			pgsz.W = xml.Attr{Name: xml.Name{Local: "w:w"}, Value: attr.Value}
用switch

2024-03-19 03:17 UTC, mabiao0525 commented on structsect.go
> +			pgsz.W = xml.Attr{Name: xml.Name{Local: "w:w"}, Value: attr.Value}
已提交，感谢教导！

2024-03-19 07:48 UTC, fumiama approved these changes

2024-03-19 07:49 UTC, merged

2024-03-19 07:49 UTC, fumiama commented
合作愉快，感谢你的贡献。