增加页面宽度高度、字体设置，增加序号等
fumiama/go-docx pull request #44
Opened 2024-12-21 14:10 UTC by l0g1n

增加

2024-12-21 15:07 UTC, fumiama requested changes

2024-12-21 15:07 UTC, fumiama commented on cmd/main/main.go
> +	"github.com/l0g1n/go-docx"
?

2024-12-21 15:07 UTC, fumiama commented on go.mod
> +module github.com/l0g1n/go-docx
?

2024-12-21 15:07 UTC, fumiama commented on structpara.go
> +			fmt.Printf("tt.Name.Local: %s\n", tt.Name.Local)
不接受任何向标准输出直接打印信息的行为，这不是一个库该做的事。

2024-12-21 15:07 UTC, fumiama commented on .idea/.gitignore
> +# Default ignored files
不要添加项目无关文件。

2024-12-21 16:41 UTC, l0g1n commented
抱歉，没太提交过，出了些问题。现在已经修复了

2024-12-22 08:19 UTC, fumiama approved these changes
thx!

2024-12-22 08:23 UTC, fumiama requested changes
请按提示修复lint。

2024-12-22 13:46 UTC, l0g1n commented
我分析提交，再完善一下。

2024-12-22 13:46 UTC, closed without merging